apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay
  namespace: mall-gf-dapr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pay
  template:
    metadata:
      labels:
        app: pay
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "pay"
        dapr.io/app-port: "28003"
        # dapr.io/config: "tracing"
    spec:
      containers:
      - name: pay
        image: registry.cn-hangzhou.aliyuncs.com/117503445/mall-gf-dapr-pay:latest
        volumeMounts:
        - name: pay-config
          mountPath: /root/manifest/config
        - name: pay-sql
          mountPath: /root/manifest/sql
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: pay-config
        configMap:
          name: pay-config
      - name: pay-sql
        configMap:
          name: pay-sql
