apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: mall-gf-dapr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "order"
        dapr.io/app-port: "28002"
        # dapr.io/config: "tracing"
    spec:
      containers:
      - name: order
        image: registry.cn-hangzhou.aliyuncs.com/117503445/mall-gf-dapr-order:latest
        volumeMounts:
        - name: order-config
          mountPath: /root/manifest/config
        - name: order-sql
          mountPath: /root/manifest/sql
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: order-config
        configMap:
          name: order-config
      - name: order-sql
        configMap:
          name: order-sql
