apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: order
  namespace: mall-gf-dapr
spec:
  loadbalancer:
    type: ewma
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: order
  namespace: mall-gf-dapr
spec:
  http:
  - name: order
    match:
      hosts:
      - mall-gf-order.r630-k8s.117503445.top
      paths:
      - /*
    backends:
    - serviceName: order
      servicePort: 80