namespace: mall-gf-dapr

resources:
- db.yaml
- ./casdoor/casdoor.yaml
- ./product/deployment.yaml
- ./product/ingress.yaml
- ./product/service.yaml

- ./order/deployment.yaml
- ./order/ingress.yaml
- ./order/service.yaml

- ./pay/deployment.yaml
- ./pay/ingress.yaml
- ./pay/service.yaml
configMapGenerator:
  - name: product-config
    files:
      - ./product/config/config.yaml
      - ./product/config/pub.pem
  - name: product-sql
    files:
      - ./product/sql/structure.sql
      - ./product/sql/dev-data.sql

  - name: order-config
    files:
      - ./order/config/config.yaml
      - ./order/config/pub.pem
  - name: order-sql
    files:
      - ./order/sql/structure.sql
      - ./order/sql/dev-data.sql

  - name: pay-config
    files:
      - ./pay/config/config.yaml
      - ./pay/config/pub.pem
  - name: pay-sql
    files:
      - ./pay/sql/structure.sql
      - ./pay/sql/dev-data.sql