apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: mall-gf-dapr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "product"
        dapr.io/app-port: "28001"
    spec:
      containers:
      - name: product
        image: registry.cn-hangzhou.aliyuncs.com/117503445/mall-gf-dapr-product
        volumeMounts:
        - name: product-config
          mountPath: /root/manifest/config
        - name: product-sql
          mountPath: /root/manifest/sql
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: product-config
        configMap:
          name: product-config
      - name: product-sql
        configMap:
          name: product-sql