apiVersion: apps/v1
kind: Deployment
metadata:
  name: casdoor
  namespace: mall-gf-dapr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casdoor
  template:
    metadata:
      labels:
        app: casdoor
    spec:
      containers:
      - name: casdoor
        image: casbin/casdoor-all-in-one:v1.152.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # volumeMounts:
        #   - mountPath: "/conf"
        #     name: config
      # volumes:
      # - configMap:
      #     name: casdoor-config
      #   name: config
---
apiVersion: v1
kind: Service
metadata:
  name: casdoor
  namespace: mall-gf-dapr
spec:
  # type: NodePort
  ports:
  - name: http
    targetPort: 8000
    port: 80
    # nodePort: 30163
  selector:
    app: casdoor
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixUpstream
metadata:
  name: casdoor
  namespace: mall-gf-dapr
spec:
  loadbalancer:
    type: ewma
---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: casdoor
  namespace: mall-gf-dapr
spec:
  http:
  - name: casdoor
    match:
      hosts:
      - casdoor.r630-k8s.117503445.top
      paths:
      - /*
    backends:
    - serviceName: casdoor
      servicePort: 80