server:
  address: ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  LogPath: "./data/log"
  dumpRouterMap: false

logger:
  Path: "./data/log"
  Level: "all"
  Stdout: true

database:
  link: "mysql:root:12345678@tcp(db:3306)/product"
  debug: true
  sqlOnBoot:
    - "./manifest/sql/structure.sql"
    - "./manifest/sql/dev-data.sql"

casdoor:
  endpoint: "http://casdoor:18000"
  clientId: "325462fc3558deaf360b"
  clientSecret: "8c1a94f8d0f58d77a37beff8b7a54f9d58a53bf9"
  organizationName: "mall"
  applicationName: "experiment-helper"